# i3status-rust configuration with Catppuccin theme

# [theme]
# name = "modern"
[theme.overrides]
# Catppuccin Mocha colors
idle_bg = "#1e1e2e"
idle_fg = "#cdd6f4"
info_bg = "#89b4fa"
info_fg = "#1e1e2e"
good_bg = "#a6e3a1"
good_fg = "#1e1e2e"
warning_bg = "#f9e2af"
warning_fg = "#1e1e2e"
critical_bg = "#f38ba8"
critical_fg = "#1e1e2e"
separator = " "
separator_bg = "#1e1e2e"
separator_fg = "#585b70"

# [icons]
# name = "awesome6"
[icons.overrides]
bat_charging = " "
bat_discharging = " "
bat_full = " "
cpu = " "
memory_mem = " "
net_up = " "
net_down = " "
net_wireless = " "
volume_empty = " "
volume_muted = " "
volume_half = " "
volume_full = " "
time = " "

# [[block]]
# block = "focused_window"
# max_width = 50
# show_marks = true

# [[block]]
# block = "cpu"
# interval = 1
# format = "${usage}"

# [[block]]
# block = "memory"
# format_mem = "{mem_used}/{mem_total} "
# format_swap = "{swap_used}/{swap_total}"
# display_type = "memory"
# icons = true
# clickable = true

# [[block]]
# block = "net"
# device = "eth0"
# format = "{ssid} {signal_strength} {speed_down} "
# interval = 5
# missing_format = ""

# [[block]]
# block = "sound"
# step_width = 3

[[block]]
block = "time"
interval = 60
# format = "%{%a %d/%m %R}"
